<div class="container">
    <div  class="row">
        <div class="col">
            <div class="card text-center">
                <img src="<?= BASE_URL.IMG_URL.'trnetwork.png' ?>" class="rounded mx-auto d-block" alt="TRNETWORK" id="logoLogin">  
              <div class="card-body">
                <form id="formAccess" method="post">
                  <div class="form-group">
                    <label for="clave">Clave de acceso</label>
                    <input type="text" class="form-control" name="clave" placeholder="Clave de acceso">
                  </div>
                  <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
                </form>
              </div>
            </div>
        </div>
    </div>
</div>
<script>
    var root = "<?php echo BASE_URL.$this->_controller.'/';?>"
    var rootAdmin = "<?php echo BASE_URL.'admin/';?>"
</script>