<section id="avisoSection">
    <div class="container" id="avisoContainer">
        <div class="row">
            <div class="col-lg text-center">
                <h1>Aviso de privacidad</h1>
            </div>
            <div class="col-lg-12">
                <strong>Políticas de Privacidad de “¿quien es TR network?”</strong>
                <p>Aviso de Privacidad</p>
                <p><strong>De la identidad y domicilio del responsable de la Protección de Datos Personales.</strong></p>
                <p>El aviso de privacidad forma parte del uso del sitio web: <strong>www.trnetwork.com.mx/quienestrnetwork</strong>
                    TR network S.A. de C.V.(en adelante TR network y/o nombre del sitio) sus empresas filiales y/o subsidiarias, tienen
                    como domicilio: Boulevard San Felipe Número 224, colonia Valle del Ángel, CP. 72040, de la ciudad de Puebla. México.</p>
                <p>Es nuestro Departamento de Protección de Datos, el responsable de proteger la confidencialidad de los datos personales de
                    los usuarios de sus servicios, así como de garantizar su privacidad y su derecho a la autodeterminación informativa y se
                    ubican en el domicilio antes mencionado, y pone a su disposición los siguientes medios de contacto; vía correo electrónico:
                    <strong>datospersonales@nombredelsitio.com</strong> o por escrito a la siguiente dirección: Boulevard San Felipe Número 224,
                    colonia Valle del Ángel, CP. 72040, de la ciudad de Puebla, México.</p>
                <p>El siguiente documento es generado de acuerdo a lo establecido por la <strong>“Ley Federal de protección de Datos Personales”</strong>
                    en posesión de los particulares, vigente actualmente en los Estados Unidos Mexicanos.</p>
                <br/>
                <p><strong>Los datos que en nombre del sitio recabamos:</strong></p>
                <p><strong>Nombre del sitio</strong>, como parte formal de su actividad, recopila información de usuarios y visitantes de la plataforma de
                    diversas maneras, desde diferentes áreas de nuestro sitio web.</p>
                <p>Se solicita información como: Nombre(s), Correo Electrónico, contraseña con la que se ingresa al sitio y en caso de ser necesario se solicitará:
                    Nombre de la empresa en que labora actualmente, la entidad federativa donde se encuentra la empresa en donde labora el usuario, el sexo del usuario
                    con el fin de configurar su perfil con una imagen de acuerdo al sexo que especifique, perfil de alguna red social de su preferencia.</p>
                <p>Al inscribirse y/o navegar en el sitio web <strong>Nombre del sitio</strong>, el usuario presta su consentimiento para que se utilice su información
                    personal de acuerdo a las disposiciones que se requieran. Todos los datos personales son tratados bajo estrictas medidas de seguridad, garantizando su confidencialidad.</p>
                <br/>
                <p><strong>Nombre del sitio </strong>en ningún momento recabará <strong style="color:red;">Datos Personales Sensibles</strong>, tales como: origen racial o étnico,
                    el estado de salud, la información genética, las creencias religiosas, filosóficas y morales, la afiliación sindical, las opiniones políticas y las preferencias sexuales.</p>
                <br>
                <p><strong>Nombre del sitio</strong>, podrá confirmar los Datos Personales suministrados acudiendo a entidades públicas o compañías especializadas, para lo cual nos autorizas
                    expresamente a corroborar esos datos, incluyendo datos financieros, con las mencionadas entidades.  La información que <strong>Nombre del sitio</strong>, obtenga de estas
                    entidades será tratada en forma confidencial.</p>
                <br/>
                <p>La responsabilidad en la veracidad de los datos proporcionados en <strong>Nombre del sitio</strong>, es exclusiva del usuario, por lo que en caso de haber otorgado algún dato falso,
                    <strong>Nombre del sitio</strong>, se reserva el derecho de negar el acceso al usuario a este sitio web. Los datos de carácter personal que proporcione el usuario serán objeto de
                    tratamiento automatizado e incorporados a: archivos y bases de datos, propiedad de <strong>Nombre del sitio</strong>, como sociedad titular y responsable de sus propios archivos.
                    <strong>Nombre del sitio </strong> <strong style="color: red;">no comparte información con terceros.</strong></p>
                <br/>
                <p>Se acuerda expresamente que en cualquier momento el usuario registrado en <strong>Nombre del sitio</strong> podrá solicitar la baja o cierre de su cuenta o eliminación de su
                    información de la base de datos de <strong>Nombre del sitio</strong></p>
                <p>Por favor revisa la sección "Medios para ejercer los derechos de acceso, rectificación, cancelación y oposición en relación con los Datos Personales”</p>
                <br/>
                <p><strong>Nombre del sitio</strong>, captura y almacena automáticamente cierta información sobre la actividad de los usuarios y visitantes dentro de su sitio web. Tal información puede
                    incluir la URL de la que provienen, a qué URL acceden continuamente, qué navegador están usando, y sus direcciones IP. También las páginas visitadas, las búsquedas realizadas.</p>
                <br/>
                <br/>
                <p><strong>Finalidad del tratamiento de los Datos Personales</strong></p>
                <br/>
                <ul>
                    <li>Con la finalidad de proveerle un servicio eficiente.</li>
                    <li>Dar seguimiento a sus actividades realizadas dentro del sitio.</li>
                    <li>Informar sobre cambios de nuestros servicios.</li>
                    <li>Personalizar, medir y mejorar su experiencia de usuario, nuestros servicios, contenidos y publicidad.</li>
                </ul>
                <br/><br/>
                <p><strong>El uso de los Datos Personales por otros Usuarios</strong></p>
                <br/>
                <p>El uso de los Datos Personales por otros Usuarios <strong>Nombre del sitio</strong>, nuestro servicio permite un acceso limitado a ciertos datos de contacto del resto de usuarios,
                    tales como Nombre de usuario, mensajes o información que haya compartido, empresa donde labora y el estado en el que reside.</p>
                <p>Los usuarios sólo podrán utilizar los Datos Personales de otros usuarios obtenidos en el sitio para: </p>
                <br/>
                <ul>
                    <li>Comparar su experiencia laboral, compartir experiencias, consejos, anécdotas, tips, recursos, enlaces, información en general.</li>
                </ul>
                <br/>
                <p><strong>Seguridad y medios para evitar el uso o divulgación de los Datos Personales. Almacenamiento y transferencia de los Datos Personales</strong></p>
                <br/>
                <p><strong>Nombre del sitio </strong>considera a los datos de sus usuarios como un activo que debe ser protegido de cualquier pérdida o acceso no autorizado, razón por la cual,
                    queda prohibida su divulgación ilícita y limita su uso a terceros, de conformidad a lo previsto en este Aviso de Privacidad. sted en cualquier momento, podrá optar por limitar el uso o
                    divulgación de sus datos personales o revocar su consentimiento para dar tratamiento a sus datos personales.</p>
                <br/>
                <p>En <strong>Nombre del sitio</strong> empleamos diversas técnicas de seguridad para proteger tales datos de accesos no autorizados por usuarios dentro o fuera de nuestra compañía.
                    Sin embargo, es necesario tener muy en cuenta que la seguridad perfecta no existe en Internet.</p>
                <br>
                <p>Bajo ninguna circunstancia, se debe comunicar Datos Personales o dirección de correo electrónico de otro usuario a ningún tercero sin nuestro consentimiento y el del usuario afectado.
                    No se debe agregar a la agenda de direcciones de correo electrónico los datos de ningún usuario de <strong>Nombre del sitio</strong></p>
                <br/>
                <p>En el caso de que el usuario facilite datos de un tercero, por ejemplo, para recomendarle a un conocido sobre nuestra web o servicios de la misma, le informamos que será el usuario el
                    responsable de haber obtenido el consentimiento de la persona, y de los datos facilitados de la misma.</p>
                <br>
                <p><strong>Medios para ejercer los derechos de acceso, rectificación, cancelación y oposición en relación con los Datos Personales. (ARCO)</strong></p>
                <br/>
                <p>Los usuarios podrán ejercitar los derechos de acceder, rectificar, cancelar y actualizar sus datos personales, así como a oponerse al tratamiento de la misma y a ser informado de las sesiones
                    llevadas a cabo, todo ello de conformidad a lo dispuesto en la normativa aplicable. Los usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad
                    de los datos personales facilitados, y se comprometen a mantenerlos debidamente actualizados.</p>
                <br/>
                <p>Una vez registrado como usuario en <strong>Nombre del sitio</strong>, el usuario podrá revisar y cambiar la información que nos ha enviado durante el proceso de registro
                    En determinados casos, mantendremos en nuestros archivos los datos personales que nos hayas pedido que retiremos, con la finalidad de resolver disputas o reclamaciones, detectar problemas o
                    incidencias y solucionarlos, por el período de tiempo que determine la normativa aplicable. En cualquier caso, los datos personales de un usuario no serán inmediatamente retirados de nuestros
                    archivos por motivos legales y técnicos, incluyendo sistemas de soportes de seguridad.</p>
                <br/>
                <p>Por tanto, no se debe esperar que todos los Datos Personales sean definitivamente borrados de nuestras bases de datos.</p>
                <br>
                <p>Para recibir mayor información sobre la confidencialidad y protección de tus datos personales, así como para el caso que desees ejercer tus derechos de acceder, rectificar, cancelar u oponerte
                    (<strong>ARCO</strong>)) al tratamiento de tus datos personales, o si quisieras revocar el consentimiento otorgado al tratamiento de sus datos en este documento, deberás de presentar una solicitud
                    a nuestro Departamento de Protección de Datos ya sea por correo electrónico a: <strong>datospersonales@nombredelsitio.com </strong>o bien por escrito a la siguiente dirección: Boulevard San Felipe
                    Número 224 en la colonia Valle del Ángel, CP. 72040, en la Heroica Puebla de Zaragoza.</p>
                <br/>
                <p>La solicitud debe contener lo siguiente:</p>
                <br/>
                <ul>
                    <li>Copia de identificación oficial del titular de los Datos Personales.</li>
                    <li>Si actúa por mandato de alguna persona física o moral, deberá acreditar su personalidad en términos del original o copia certificada de carta poder</li>
                    <li>Señalar domicilio o medio para recibir notificaciones.</li>
                    <li>La explicación clara y precisa de los datos personales a los cuales quieres tener acceso, rectificación, cancelación u oposición.</li>
                    <li>Cualquier otro elemento o documento que facilite la localización de tus datos personales.</li>
                </ul>
                <p>
                    Es importante conservar la constancia de la solicitud que presentaste pues si no obtuviste respuesta o no quedaste satisfecho puedes acudir al Instituto Nacional de Transparencia, Acceso a la Información
                    y Protección de Datos Personales (INAI). La constancia será indispensable.
                </p>
                <p>Puedes contactar a nuestro Departamento de Protección de Datos por correo electrónico a <strong>datospersonales@nombredelsitio.com</strong>com o por escrito a la siguiente dirección: Boulevard San Felipe
                    Número 224 en la colonia Valle del Ángel, CP. 72040, en la Heroica Puebla de Zaragoza.</p>
                <br>
                <p>Una vez presentada la solicitud para ejercer sus derechos de ARCO, debidamente integrada y con los requisitos legales vigentes, nuestro responsable analizará la solicitud y tendrá un plazo máximo de 20 días hábiles para responder.
                    Si fuere procedente su solicitud, se hará efectiva dentro de los 15 días hábiles siguientes a que le hayamos comunicado nuestra respuesta. Los plazos podrán ser ampliados por una sola vez y por un periodo igual cuando existan hechos que lo justifiquen.</p>
                <br/>
                <p>En caso de estar inconforme con la respuesta enviada, tendrá un plazo de 20 días hábiles para ponerse en contacto con nosotros, indicando de forma puntual y clara su inconformidad o inquietud, con la finalidad de resolver dicha situación, en caso de no
                    responder la notificación manifestando su conformidad, <strong>Nombre del sitio</strong>, entenderá de buena fe que está conforme con nuestra respuesta.</p>
                <br/>
                <p><strong>Confidencialidad de los Datos Personales</strong></p>
                <br/>
                <p>Una vez suscrito en nuestro sitio web, <strong>Nombre del sitio</strong>, no venderá, alquilará o compartirá los Datos Personales excepto en las formas establecidas en este Aviso de Privacidad. Haremos todo lo que esté a nuestro alcance para proteger la
                    privacidad de la información. Puede suceder que, en virtud de órdenes judiciales, o de regulaciones legales, nos veamos comprometidos a revelar información a las autoridades o terceras partes bajo ciertas circunstancias.</p>
                <p><strong>Nombre del sitio</strong>sitio ha adoptado los niveles de seguridad de protección de datos personales legalmente requeridos por <strong>“Ley Federal de Protección de Datos Personales en Posesión de los Particulares” </strong>bajo los principios de licitud,
                    consentimiento, información, calidad, finalidad, lealtad, proporcionalidad y responsabilidad en el tratamiento de datos personales. Todo esto bajo estrictas reglas de seguridad, confidencialidad y consistencia de información.</p>
                <br/>
                <p><strong>Cookies</strong></p>
                <br/>
                <p>El usuario y el visitante del sitio web de <strong>Nombre del sitio</strong>, conoce y acepta que <strong>Nombre del sitio</strong>, podrá utilizar un sistema de seguimiento mediante la utilización de cookies.</p>
                <br/>
                <p>Las Cookies son pequeños archivos que se instalan en el disco rígido, con una duración limitada en el tiempo que ayudan a personalizar los servicios. También ofrecemos ciertas funcionalidades que sólo están disponibles mediante el empleo de Cookies. Las Cookies se utilizan
                    con el fin de conocer los intereses, el comportamiento y la demografía de quienes visitan o son usuarios de <strong>Nombre del sitio</strong>sitio y de esa forma, comprender mejor sus necesidades e intereses y darles un mejor servicio o proveerle información relacionada.
                    También usaremos la información obtenida por intermedio de las Cookies para analizar las páginas navegadas por el visitante o usuario, las búsquedas realizadas, mejorar nuestras iniciativas promocionales, mostrar publicidad o promociones, banners de interés, noticias sobre
                    <strong>Nombre del sitio</strong>, perfeccionar nuestra oferta de contenidos y artículos, personalizar dichos contenidos, presentación y servicios; también podremos utilizar Cookies para promover y hacer cumplir las reglas y seguridad del sitio.</p>
                <br/>
                <p>Utilizamos adicionalmente las Cookies para que el usuario no tenga que introducir su clave tan frecuentemente durante una sesión de navegación, también para contabilizar y corroborar las inscripciones y la actividad del usuario. <br>Se establece que la instalación, permanencia
                    y existencia de las Cookies en el computador del usuario depende de su exclusiva voluntad y puede ser eliminada de su equipo cuando el usuario así lo desee. <br>Para saber como quitar las Cookies del sistema es necesario revisar la sección “Ayuda” que se encuentra en la barra
                    de herramientas de la mayoría de los navegadores, le dirá como evitar aceptar nuevos cookies, como hacer que el navegador le notifique cuando reciba un nuevo cookie o como deshabilitar todos los cookies.</p>
                <p>Se aclara expresamente que este Aviso de Privacidad cubre la utilización de Cookies por este sitio y no la utilización de Cookies por parte de anunciantes. Nosotros no controlamos el uso de Cookies por terceros.</p>
                <br/>
                <p><strong>Procedimiento para comunicar los cambios al Aviso de Privacidad</strong><br><br>
                    En <strong>Nombre del sitio </strong>nos reservamos el derecho de efectuar en cualquier momento modificaciones o actualizaciones al presente aviso de privacidad, para la atención de novedades legislativas o jurisprudenciales, políticas internas, nuevos requerimientos para la
                    prestación u ofrecimiento de nuestros servicios o productos y prácticas del mercado.</p>
                <br/>
                <p>Nos comprometemos a mantenerlo informado sobre los cambios que pueda sufrir el presente aviso de privacidad y estás modificaciones estarán disponibles al público a través de nuestro sitio web <strong>Nombre del sitio </strong> en la sección <strong>“Aviso de Privacidad”</strong>
                    o se las haremos llegar vía correo electrónico para mantenerlo actualizado de los cambios realizados.</p>
                <br/>
                <p><strong>Aceptación de los Términos</strong><br><br>
                    Esta declaración de Privacidad está sujeta a los términos y condiciones del sitio web de <strong>Nombre del sitio</strong>, lo cual constituye un acuerdo legal entre el usuario y <strong>Nombre del sitio</strong>.</p>
                <br/>
                <p>Si el usuario considera que han sido vulnerados sus derechos respecto de la protección de datos personales, tiene el derecho de acudir a la autoridad correspondiente a efecto de defender su ejercicio. La autoridad es el Instituto Nacional de Transparencia, Acceso a la Información y
                    Protección de Datos Personales (INAI), su sitio web es: http://inicio.inai.org.mx/</p>
                <p>Manifiesto bajo protesta de decir verdad que, he leído en su totalidad el contenido del presente aviso de privacidad integral, y el cual, además de que lo entiendo cabalmente, estoy de acuerdo en todos sus términos del presente aviso de privacidad.</p>
                <br/>
                <form id="formAviso">
                    <input type='radio' id='radio_1' name='type' value='1' /> SI<br>
                    <input type='radio' id='radio_2' name='type' value='0' /> No<br>
                    <br/>
                    <input type="submit" name="enviar" value="Aceptar">
                </form>
                <br/>
                <p>Estimado usuario, se le notifica que el Aviso de Privacidad ha sido modificado el
                    día <strong> 06 de Agosto del 2018. </strong></p>
            </div>
        </div>
    </div>
</section>