<?php
/**
 * Created by PhpStorm.
 * User: Dani
 * Date: 29/06/2019
 * Time: 10:31 AM
 */
date_default_timezone_set('America/Mexico_city');
$fecha = date("Y-m-d H:i:s");
?>
<div class="container">
    <div class="row">
        <div class="col">
        	<div class="card text-center">
        		<img src="<?= BASE_URL.IMG_URL.'trnetwork.png' ?>" class="rounded mx-auto d-block" alt="TRNETWORK" id="logoLogin">	
			  <div class="card-body">
			    <form id="formLogin" method="post">
				  <div class="form-group">
				    <label for="exampleInputEmail1">Correo electronico</label>
				    <input type="email" class="form-control" id="correo" name="correo" aria-describedby="emailHelp" placeholder="E-mail" required>
				  </div>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Contraseña</label>
				    <input type="password" class="form-control" id="contrasena" name="contrasena" placeholder="Contraseña" required>
				  </div>
				  <div class="g-recaptcha" data-sitekey="6LffE88UAAAAAEl2m_i-PtyBBP9ssshAm8cbxVOo" id="captcha" required></div>
				  <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
				</form>
			  </div>
			</div>
        </div>
    </div>
</div>
<script src='https://www.google.com/recaptcha/api.js'></script>
<script>
    var root = "<?php echo BASE_URL.$this->_controller.'/'; ?>";
    var rootImage = "<?php echo BASE_URL.'views/'.$this->_controller.'/img/';?>";
</script>